/**
 * Rubric model with multiple dimensions
 */
const mongoose = require('mongoose');

const rubricDimensionSchema = new mongoose.Schema({
    name: {
        type: String,
        required: [true, 'Dimension name is required'],
        trim: true
    },
    description: {
        type: String,
        required: [true, 'Dimension description is required'],
        trim: true
    },
    weight: {
        type: Number,
        default: 1.0,
        min: [0, 'Weight cannot be negative']
    },
    maxPoints: {
        type: Number,
        default: 100
    },
    keywords: [{
        type: String,
        trim: true
    }],
    order: {
        type: Number,
        default: 0
    }
}, { _id: true });

const rubricSchema = new mongoose.Schema({
    name: {
        type: String,
        required: [true, 'Rubric name is required'],
        trim: true
    },
    description: {
        type: String,
        trim: true
    },
    dimensions: {
        type: [rubricDimensionSchema],
        validate: {
            validator: function(dims) {
                return dims && dims.length > 0;
            },
            message: 'At least one rubric dimension is required'
        }
    },
    question: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Question'
    },
    createdBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    isTemplate: {
        type: Boolean,
        default: false
    },
    isAutoGenerated: {
        type: Boolean,
        default: false
    }
}, {
    timestamps: true
});

// Indexes
rubricSchema.index({ createdBy: 1 });
rubricSchema.index({ question: 1 });

// Method to normalize weights
rubricSchema.methods.normalizeWeights = function() {
    const totalWeight = this.dimensions.reduce((sum, dim) => sum + dim.weight, 0);
    if (totalWeight > 0) {
        this.dimensions.forEach(dim => {
            dim.weight = dim.weight / totalWeight;
        });
    }
};

// Pre-save hook to sort dimensions by order
rubricSchema.pre('save', function(next) {
    this.dimensions.sort((a, b) => a.order - b.order);
    next();
});

module.exports = mongoose.model('Rubric', rubricSchema);