import React, { useState, useEffect } from 'react';
import { rubricsAPI, questionsAPI } from '../api';

const ManageRubrics = () => {
    const [rubrics, setRubrics] = useState([]);
    const [questions, setQuestions] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    const [showCreateModal, setShowCreateModal] = useState(false);
    const [editingRubric, setEditingRubric] = useState(null);

    useEffect(() => {
        fetchData();
    }, []);

    const fetchData = async () => {
        try {
            setLoading(true);
            const [rubricsRes, questionsRes] = await Promise.all([
                rubricsAPI.getAll(),
                questionsAPI.getAll()
            ]);
            setRubrics(rubricsRes.data.data || []);
            setQuestions(questionsRes.data.data || []);
        } catch (err) {
            setError('Failed to load data');
        } finally {
            setLoading(false);
        }
    };

    const handleDelete = async (id) => {
        if (!window.confirm('Are you sure you want to delete this rubric?')) return;
        
        try {
            await rubricsAPI.delete(id);
            setRubrics(rubrics.filter(r => r._id !== id));
        } catch (err) {
            alert('Failed to delete rubric');
        }
    };

    const handleNormalize = async (id) => {
        try {
            await rubricsAPI.normalize(id);
            fetchData();
        } catch (err) {
            alert('Failed to normalize weights');
        }
    };

    if (loading) {
        return <div className="loading">Loading...</div>;
    }

    return (
        <div className="manage-rubrics-page">
            <div className="page-header">
                <h1>Manage Rubrics</h1>
                <button 
                    onClick={() => setShowCreateModal(true)}
                    className="btn btn-primary"
                >
                    + Create Rubric
                </button>
            </div>

            {error && <div className="alert alert-error">{error}</div>}

            <div className="rubrics-list">
                {rubrics.length === 0 ? (
                    <p className="empty-state">No rubrics created yet. Click "Create Rubric" to get started.</p>
                ) : (
                    rubrics.map(rubric => (
                        <div key={rubric._id} className="rubric-card">
                            <div className="rubric-header">
                                <h3>{rubric.name}</h3>
                                <div className="rubric-badges">
                                    {rubric.isTemplate && (
                                        <span className="badge badge-template">Template</span>
                                    )}
                                    {rubric.isAutoGenerated && (
                                        <span className="badge badge-auto">Auto-generated</span>
                                    )}
                                </div>
                            </div>
                            
                            {rubric.description && (
                                <p className="rubric-description">{rubric.description}</p>
                            )}

                            {rubric.question && (
                                <p className="linked-question">
                                    <strong>Linked to:</strong> {rubric.question.title || rubric.question}
                                </p>
                            )}

                            <div className="dimensions-preview">
                                <h4>Dimensions ({rubric.dimensions?.length || 0})</h4>
                                <ul>
                                    {rubric.dimensions?.slice(0, 4).map((dim, idx) => (
                                        <li key={idx}>
                                            <strong>{dim.name}</strong>
                                            <span className="weight">
                                                (Weight: {(dim.weight * 100).toFixed(0)}%)
                                            </span>
                                            <p className="dim-desc">{dim.description?.substring(0, 80)}...</p>
                                        </li>
                                    ))}
                                    {rubric.dimensions?.length > 4 && (
                                        <li className="more">
                                            +{rubric.dimensions.length - 4} more dimensions
                                        </li>
                                    )}
                                </ul>
                            </div>

                            <div className="rubric-actions">
                                <button 
                                    onClick={() => setEditingRubric(rubric)}
                                    className="btn btn-sm btn-secondary"
                                >
                                    Edit
                                </button>
                                <button 
                                    onClick={() => handleNormalize(rubric._id)}
                                    className="btn btn-sm btn-secondary"
                                    title="Normalize weights to sum to 1"
                                >
                                    Normalize
                                </button>
                                <button 
                                    onClick={() => handleDelete(rubric._id)}
                                    className="btn btn-sm btn-danger"
                                >
                                    Delete
                                </button>
                            </div>
                        </div>
                    ))
                )}
            </div>

            {(showCreateModal || editingRubric) && (
                <RubricModal
                    rubric={editingRubric}
                    questions={questions}
                    onClose={() => {
                        setShowCreateModal(false);
                        setEditingRubric(null);
                    }}
                    onSave={() => {
                        fetchData();
                        setShowCreateModal(false);
                        setEditingRubric(null);
                    }}
                />
            )}
        </div>
    );
};

// Rubric Modal Component
const RubricModal = ({ rubric, questions, onClose, onSave }) => {
    const [formData, setFormData] = useState({
        name: rubric?.name || '',
        description: rubric?.description || '',
        questionId: rubric?.question?._id || rubric?.question || '',
        isTemplate: rubric?.isTemplate || false,
        dimensions: rubric?.dimensions?.length > 0 
            ? rubric.dimensions.map(d => ({
                name: d.name || '',
                description: d.description || '',
                weight: d.weight || 1,
                keywords: d.keywords?.join(', ') || ''
            }))
            : [{ name: '', description: '', weight: 1, keywords: '' }]
    });
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');

    const handleChange = (e) => {
        const { name, value, type, checked } = e.target;
        setFormData({
            ...formData,
            [name]: type === 'checkbox' ? checked : value
        });
    };

    const handleDimensionChange = (idx, field, value) => {
        const newDimensions = [...formData.dimensions];
        newDimensions[idx] = { ...newDimensions[idx], [field]: value };
        setFormData({ ...formData, dimensions: newDimensions });
    };

    const addDimension = () => {
        setFormData({
            ...formData,
            dimensions: [...formData.dimensions, { name: '', description: '', weight: 1, keywords: '' }]
        });
    };

    const removeDimension = (idx) => {
        if (formData.dimensions.length <= 1) {
            alert('At least one dimension is required');
            return;
        }
        setFormData({
            ...formData,
            dimensions: formData.dimensions.filter((_, i) => i !== idx)
        });
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setLoading(true);
        setError('');

        // Validate dimensions
        const validDimensions = formData.dimensions.filter(d => d.name.trim() && d.description.trim());
        if (validDimensions.length === 0) {
            setError('At least one dimension with name and description is required');
            setLoading(false);
            return;
        }

        try {
            const payload = {
                name: formData.name,
                description: formData.description,
                questionId: formData.questionId || undefined,
                isTemplate: formData.isTemplate,
                dimensions: validDimensions.map((dim, idx) => ({
                    name: dim.name.trim(),
                    description: dim.description.trim(),
                    weight: parseFloat(dim.weight) || 1,
                    keywords: dim.keywords ? dim.keywords.split(',').map(k => k.trim()).filter(Boolean) : [],
                    order: idx
                }))
            };

            if (rubric) {
                await rubricsAPI.update(rubric._id, payload);
            } else {
                await rubricsAPI.create(payload);
            }
            onSave();
        } catch (err) {
            setError(err.response?.data?.message || 'Failed to save rubric');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="modal-overlay" onClick={onClose}>
            <div className="modal rubric-modal" onClick={e => e.stopPropagation()}>
                <div className="modal-header">
                    <h2>{rubric ? 'Edit Rubric' : 'Create Rubric'}</h2>
                    <button className="modal-close" onClick={onClose}>&times;</button>
                </div>
                
                {error && <div className="alert alert-error">{error}</div>}

                <form onSubmit={handleSubmit}>
                    <div className="form-group">
                        <label>Rubric Name *</label>
                        <input
                            type="text"
                            name="name"
                            value={formData.name}
                            onChange={handleChange}
                            required
                            placeholder="e.g., Neural Networks Grading Rubric"
                        />
                    </div>

                    <div className="form-group">
                        <label>Description</label>
                        <textarea
                            name="description"
                            value={formData.description}
                            onChange={handleChange}
                            rows={2}
                            placeholder="Brief description of what this rubric evaluates"
                        />
                    </div>

                    <div className="form-group">
                        <label>Link to Question (optional)</label>
                        <select
                            name="questionId"
                            value={formData.questionId}
                            onChange={handleChange}
                        >
                            <option value="">-- Select a Question --</option>
                            {questions.map(q => (
                                <option key={q._id} value={q._id}>{q.title}</option>
                            ))}
                        </select>
                    </div>

                    <div className="form-group checkbox-group">
                        <label>
                            <input
                                type="checkbox"
                                name="isTemplate"
                                checked={formData.isTemplate}
                                onChange={handleChange}
                            />
                            Save as reusable template
                        </label>
                    </div>

                    <div className="dimensions-section">
                        <div className="dimensions-header">
                            <h3>Rubric Dimensions</h3>
                            <small>Each dimension represents a criterion for evaluation</small>
                        </div>
                        
                        {formData.dimensions.map((dim, idx) => (
                            <div key={idx} className="dimension-form">
                                <div className="dimension-number">#{idx + 1}</div>
                                <div className="dimension-fields">
                                    <div className="form-row">
                                        <div className="form-group">
                                            <label>Dimension Name *</label>
                                            <input
                                                type="text"
                                                placeholder="e.g., Concept Understanding"
                                                value={dim.name}
                                                onChange={(e) => handleDimensionChange(idx, 'name', e.target.value)}
                                                required
                                            />
                                        </div>
                                        <div className="form-group weight-input">
                                            <label>Weight</label>
                                            <input
                                                type="number"
                                                placeholder="1.0"
                                                value={dim.weight}
                                                onChange={(e) => handleDimensionChange(idx, 'weight', e.target.value)}
                                                min={0}
                                                step={0.1}
                                            />
                                        </div>
                                    </div>
                                    <div className="form-group">
                                        <label>Description/Requirement *</label>
                                        <textarea
                                            placeholder="What should the student demonstrate for this criterion?"
                                            value={dim.description}
                                            onChange={(e) => handleDimensionChange(idx, 'description', e.target.value)}
                                            rows={2}
                                            required
                                        />
                                    </div>
                                    <div className="form-group">
                                        <label>Keywords (comma-separated)</label>
                                        <input
                                            type="text"
                                            placeholder="e.g., neurons, layers, activation"
                                            value={dim.keywords}
                                            onChange={(e) => handleDimensionChange(idx, 'keywords', e.target.value)}
                                        />
                                    </div>
                                </div>
                                {formData.dimensions.length > 1 && (
                                    <button 
                                        type="button"
                                        onClick={() => removeDimension(idx)}
                                        className="btn-remove-dimension"
                                        title="Remove dimension"
                                    >
                                        &times;
                                    </button>
                                )}
                            </div>
                        ))}
                        
                        <button 
                            type="button"
                            onClick={addDimension}
                            className="btn btn-add-dimension"
                        >
                            + Add Another Dimension
                        </button>
                    </div>

                    <div className="modal-actions">
                        <button type="button" onClick={onClose} className="btn btn-secondary">
                            Cancel
                        </button>
                        <button type="submit" className="btn btn-primary" disabled={loading}>
                            {loading ? 'Saving...' : (rubric ? 'Update Rubric' : 'Create Rubric')}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default ManageRubrics;